// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

::uniffi::setup_scaffolding!("crypto_service");

/// Export info about the UDL while used to create us
/// See `uniffi_bindgen::macro_metadata` for how this is used.

// ditto for info about the UDL which spawned us.

const UNIFFI_META_CONST_UDL_CRYPTO_SERVICE: ::uniffi::MetadataBuffer =
    ::uniffi::MetadataBuffer::from_code(::uniffi::metadata::codes::UDL_FILE)
        .concat_str("crypto_service")
        .concat_str("crypto_service")
        .concat_str("crypto_service");

#[doc(hidden)]
#[no_mangle]
pub static UNIFFI_META_UDL_CRYPTO_SERVICE: [u8; UNIFFI_META_CONST_UDL_CRYPTO_SERVICE.size] =
    UNIFFI_META_CONST_UDL_CRYPTO_SERVICE.into_array();

// Record definitions, implemented as method-less structs, corresponding to `dictionary` objects.

// Top level functions, corresponding to UDL `namespace` functions.// Object definitions, corresponding to UDL `interface` definitions.

// Callback Interface definitions, corresponding to UDL `callback interface` definitions.

// External and Wrapped types
// Support for external types.

// Types with an external `FfiConverter`...

// We generate support for each Custom Type and the builtin type it uses.

// Export scaffolding checksums for UDL items
